# This file was *autogenerated* from the file prac.sage
from sage.all_cmdline import *   # import sage library
_sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/bin/env python

from sage.all import *
x = _sage_const_100 
cnt = _sage_const_0 
for i in xrange(_sage_const_1 , x):
    if gcd(i, x) == _sage_const_1 :
        print i
        cnt = cnt + _sage_const_1 

    
