# This file was *autogenerated* from the file prac.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10001 = Integer(10001); _sage_const_444266014606582911577255360081280172978907874637194279031281180366057 = Integer(444266014606582911577255360081280172978907874637194279031281180366057)
def fast_power(a,n):
    print "%s %s" % (a, n)
    result = _sage_const_1 
    value = a
    power = n
    while power > _sage_const_0 :
        if power % _sage_const_2  == _sage_const_1 :
            result = result * value
        value = value * value
    power = power/_sage_const_2 
    return result


n = _sage_const_444266014606582911577255360081280172978907874637194279031281180366057 
c = _sage_const_0 
c_last = _sage_const_2 
for i in range(_sage_const_2 , _sage_const_10001 ):
    c = fast_power(c_last, i)
    c = c mod n
    c_last = c
print c
